---
- name: Deber
  hosts: node1
  become: true
  tasks: 
  
  - name: Cear Usuario student
    user:
      name: student6
      uid: 4545
      state: present
      
  - name: Imprimir
    debug:
      msg: "Hola Mundo"


