---
- name: Deber
  hosts: test
  become: true
  task: 
  - name: Cear Usuario student
    user:
      name: student6
      uid: 4545
      state: present
      
  - name: Imprimir
    debug:
      msg: "Hola Mundo"


